language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm run build
#  - npm test -- --coverage
#after_script: # Upload coverage reports 
#  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
after_failure:
  - cat *debug.log
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: iteration-2